name: Build
on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    name: "build"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [2.0.0]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: yarn install --frozen-lockfile

      - name: run prettier checker
        run: yarn run prettier:check

      - name: run tests
        run: yarn run test

      - name: check publish
        run: yarn run publish:check
